config/routes.rb
Rails.application.routes.draw do
  resources :trustees do
    resources :account_systems
  end
  

  root 'trustees#index'

end

app/models/account_system.rb
class AccountSystem < ActiveRecord::Base
end

app/models/trustee.rb
class Trustee < ActiveRecord::Base
	has_many :account_systems
end

app/controllers/account_systems_controller.rb
class AccountSystemsController < ApplicationController
  skip_before_filter :verify_authenticity_token, :if => Proc.new { |c| c.request.format == 'application/json' }
  before_filter :load_trustee

  def create
    @account_system = AccountSystem.new(account_system_params)
    @account_system.save
    redirect_to trustee_account_systems_path(@trustee, @account_system), notice: 'Account system was successfully created.'
  end

  def account_system_params
     params.require(:account_system).permit(:iban)
  end

  private

    def load_trustee
      @trustee = Trustee.find(params[:trustee_id])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/trustees_controller.rb
class TrusteesController < ApplicationController
  skip_before_filter :verify_authenticity_token, :if => Proc.new { |c| c.request.format == 'application/json' }
  before_action :set_trustee, only: [:show, :edit, :update, :destroy]

  # GET /trustees
  # GET /trustees.json
  def index
    @trustees = Trustee.includes(:account_systems).all
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @trustees.to_json(:include => :account_systems) }
    end
  end

  # GET /trustees/1
  # GET /trustees/1.json
  def show
  end

  # GET /trustees/new
  def new
    @trustee = Trustee.new
  end

  # GET /trustees/1/edit
  def edit
  end

  # POST /trustees
  # POST /trustees.json
  def create
    @trustee = Trustee.new(trustee_params)

    respond_to do |format|
      if @trustee.save
        format.html { redirect_to @trustee, notice: 'Trustee was successfully created.' }
        format.json { render :show, status: :created, location: @trustee }
      else
        format.html { render :new }
        format.json { render json: @trustee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trustees/1
  # PATCH/PUT /trustees/1.json
  def update
    respond_to do |format|
      if @trustee.update(trustee_params)
        format.html { redirect_to @trustee, notice: 'Trustee was successfully updated.' }
        format.json { render :show, status: :ok, location: @trustee }
      else
        format.html { render :edit }
        format.json { render json: @trustee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trustees/1
  # DELETE /trustees/1.json
  def destroy
    @trustee.destroy
    respond_to do |format|
      format.html { redirect_to trustees_url, notice: 'Trustee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trustee
      @trustee = Trustee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trustee_params
      params.require(:trustee).permit(:name, :email)
    end
end

app/helpers/account_systems_helper.rb
module AccountSystemsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trustees_helper.rb
module TrusteesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Treubuilder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/trustees/_form.html.erb
<%= form_for(@trustee) do |f| %>
  <% if @trustee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trustee.errors.count, "error") %> prohibited this trustee from being saved:</h2>

      <ul>
      <% @trustee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trustees/edit.html.erb
<h1>Editing Trustee</h1>

<%= render 'form' %>

<%= link_to 'Show', @trustee %> |
<%= link_to 'Back', trustees_path %>

app/views/trustees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Alle Treuhänder</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trustees.each do |trustee| %>
      <tr>
        <td><%= trustee.name %></td>
        <td><%= trustee.email %></td>
        <td><%= link_to 'Show', trustee %></td>
        <td><%= link_to 'Edit', edit_trustee_path(trustee) %></td>
        <td><%= link_to 'Destroy', trustee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trustee', new_trustee_path %>

app/views/trustees/new.html.erb
<h1>Neuer Treuhänder</h1>

<%= render 'form' %>

<%= link_to 'Back', trustees_path %>

app/views/trustees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @trustee.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @trustee.email %>
</p>

<%= link_to 'Edit', edit_trustee_path(@trustee) %> |
<%= link_to 'Back', trustees_path %>